import Vue from "vue";
import VueI18n from "vue-i18n";

Vue.use(VueI18n);

const messages = {
  en: {
    welcomeMsg:
      "Welcome to  internationalization Test Prototype With VueJS and i18n",
    guide: "Brief explanation of outer space",
    text:
      "Outer space is the expanse that exists beyond Earth and between celestial bodies. Outer space is not completely empty—it is a hard vacuum containing a low density of particles, predominantly a plasma of hydrogen and helium, as well as electromagnetic radiation, magnetic fields, neutrinos, dust, and cosmic rays. The baseline temperature of outer space, as set by the background radiation from the Big Bang, is 2.7 kelvins (−270.45 °C; −454.81 °F).[1] The plasma between galaxies accounts for about half of the baryonic (ordinary) matter in the universe; it has a number density of less than one hydrogen atom per cubic metre and a temperature of millions of kelvins.[2] Local concentrations of matter have condensed into stars and galaxies. Studies indicate that 90% of the mass in most galaxies is in an unknown form, called dark matter, which interacts with other matter through gravitational but not electromagnetic forces.[3][4] Observations suggest that the majority of the mass-energy in the observable universe is dark energy, a type of vacuum energy that is poorly understood.[5][6] Intergalactic space takes up most of the volume of the universe, but even galaxies and star systems consist almost entirely of empty space.",
    formationTitle: "Formation and state",
    formationText:
      "The size of the whole universe is unknown, and it might be infinite in extent.[9] According to the Big Bang theory, the very early Universe was an extremely hot and dense state about 13.8 billion years ago[10] which rapidly expanded. About 380,000 years later the Universe had cooled sufficiently to allow protons and electrons to combine and form hydrogen—the so-called recombination epoch. When this happened, matter and energy became decoupled, allowing photons to travel freely through the continually expanding space.[11] Matter that remained following the initial expansion has since undergone gravitational collapse to create stars, galaxies and other astronomical objects, leaving behind a deep vacuum that forms what is now called outer space.[12] As light has a finite velocity, this theory also constrains the size of the directly observable universe.[11]",
    enviromentTitle: "Environment",
    enviromentText:
      "Outer space is the closest known approximation to a perfect vacuum. It has effectively no friction, allowing stars, planets, and moons to move freely along their ideal orbits, following the initial formation stage. The deep vacuum of intergalactic space is not devoid of matter, as it contains a few hydrogen atoms per cubic meter.[18] By comparison, the air humans breathe contains about 1025 molecules per cubic meter.[19][20] The low density of matter in outer space means that electromagnetic radiation can travel great distances without being scattered: the mean free path of a photon in intergalactic space is about 1023 km, or 10 billion light years.[21] In spite of this, extinction, which is the absorption and scattering of photons by dust and gas, is an important factor in galactic and intergalactic astronomy.[22]",
  },

  es: {
    welcomeMsg:
      "Bienvenido al prototipo de prueba de internacionalización con VueJS e i18n",
    guide: "Breve explicación del espacio sideral",
    text:
      "El espacio exterior, el espacio exterior o simplemente el espacio es el área física completa del universo no ocupada por cuerpos celestes.Este entorno consiste en un vacío parcial que contiene partículas de baja densidad, predominantemente plasma de hidrógeno y helio, además de radiación electromagnética, campos magnéticos, neutrinos, polvo interestelar y rayos cósmicos. Su temperatura promedio, definida a partir de la radiación de fondo del Big Bang, es de 2.727 K (-270.423 ° C; -454.7614 ° F). [2] El plasma con una densidad numérica inferior a un átomo de hidrógeno por metro cúbico y una temperatura de millones de kelvin en el entorno intergaláctico representa la mayor parte de la materia bariónica espacial, que, en concentraciones locales, se integra en la formación de estrellas y galaxias. Las observaciones han proporcionado evidencia de que el 90% de la masa presente en la mayoría de las galaxias es de un tipo poco conocido, llamado materia oscura, que interactúa con otra materia por medio de fuerzas gravitacionales, pero no electromagnéticas. [3] [4] Los datos indican que la mayor parte de la masa-energía en el universo observable se entiende de alguna manera como una forma de energía del vacío, apodada por los astrónomos como energía oscura. El entorno intergaláctico ocupa la mayor parte del universo, pero incluso las galaxias y los sistemas estelares consisten casi en su totalidad en vacíos.",
    formationTitle: "Formación y estado",
    formationText:
      "Se desconoce el tamaño de todo el universo, y su extensión podría ser infinita. Según la teoría del Big Bang, el Universo muy temprano era un estado extremadamente caliente y denso hace unos 13.800 millones de años [10] que se expandió rápidamente. Aproximadamente 380.000 años después, el Universo se había enfriado lo suficiente como para permitir que los protones y los electrones se combinaran y formaran hidrógeno, la llamada época de recombinación. Cuando esto sucedió, la materia y la energía se desacoplaron, permitiendo que los fotones viajen libremente a través del espacio en continua expansión. [11] La materia que permaneció después de la expansión inicial ha sufrido un colapso gravitacional para crear estrellas, galaxias y otros objetos astronómicos, dejando un vacío profundo que forma lo que ahora se llama espacio exterior. [12] Como la luz tiene una velocidad finita, esta teoría también restringe el tamaño del universo directamente observable. [11]",
    enviromentTitle: "Medio ambiente",
    enviromentText:
      " El espacio exterior es la aproximación conocida más cercana a un vacío perfecto. Efectivamente, no tiene fricción, lo que permite que las estrellas, los planetas y las lunas se muevan libremente a lo largo de sus órbitas ideales, después de la etapa de formación inicial. El profundo vacío del espacio intergaláctico no está desprovisto de materia, ya que contiene unos pocos átomos de hidrógeno por metro cúbico. [18] En comparación, el aire que respiran los humanos contiene alrededor de 1025 moléculas por metro cúbico. [19] [20] La baja densidad de materia en el espacio exterior significa que la radiación electromagnética puede viajar grandes distancias sin dispersarse: la trayectoria libre media de un fotón en el espacio intergaláctico es de unos 1023 km, o 10 mil millones de años luz. [21] A pesar de esto, la extinción, que es la absorción y dispersión de fotones por el polvo y el gas, es un factor importante en la astronomía galáctica e intergaláctica. [22]",
  },

  br: {
    welcomeMsg:
      "Bem-vindo ao protótipo de teste de internacionalização com VueJS e i18n",
    guide: "Breve explicação do espaço sideral",
    text:
      "O espaço exterior é a extensão que existe além da Terra e entre os corpos celestes. O espaço exterior não está completamente vazio - é um vácuo rígido contendo uma baixa densidade de partículas, predominantemente um plasma de hidrogênio e hélio, bem como radiação eletromagnética, campos magnéticos, neutrinos, poeira e raios cósmicos. A temperatura da linha de base do espaço sideral, conforme definida pela radiação de fundo do Big Bang, é 2,7 kelvins (-270,45 ° C; -454,81 ° F). [1] O plasma entre as galáxias é responsável por cerca de metade da matéria bariônica (comum) do universo; tem uma densidade numérica de menos de um átomo de hidrogênio por metro cúbico e uma temperatura de milhões de Kelvin. [2] Concentrações locais de matéria se condensaram em estrelas e galáxias. Estudos indicam que 90% da massa na maioria das galáxias está em uma forma desconhecida, chamada matéria escura, que interage com outra matéria por meio de forças gravitacionais, mas não eletromagnéticas. [3] [4] As observações sugerem que a maioria da massa-energia no universo observável é a energia escura, um tipo de energia do vácuo que é mal compreendido. [5] [6] O espaço intergaláctico ocupa a maior parte do volume do universo, mas mesmo as galáxias e os sistemas estelares consistem quase inteiramente de espaço vazio.",
    formationTitle: "Formação e estado",
    formationText:
      " O tamanho de todo o universo é desconhecido e pode ser infinito em extensão. [9] De acordo com a teoria do Big Bang, o início do Universo era um estado extremamente quente e denso há cerca de 13,8 bilhões de anos [10], que se expandiu rapidamente. Cerca de 380.000 anos depois, o Universo esfriou o suficiente para permitir que prótons e elétrons se combinassem e formassem hidrogênio - a chamada época de recombinação. Quando isso aconteceu, a matéria e a energia ficaram desacopladas, permitindo que os fótons viajassem livremente pelo espaço em contínua expansão. [11] A matéria que permaneceu após a expansão inicial sofreu colapso gravitacional para criar estrelas, galáxias e outros objetos astronômicos, deixando para trás um vácuo profundo que forma o que agora é chamado de espaço sideral. [12] Como a luz tem velocidade finita, essa teoria também restringe o tamanho do universo diretamente observável. [11]",
    enviromentTitle: "Meio Ambiente",
    enviromentText:
      "O espaço exterior é a aproximação conhecida mais próxima de um vácuo perfeito. Ele efetivamente não tem atrito, permitindo que estrelas, planetas e luas se movam livremente ao longo de suas órbitas ideais, seguindo o estágio de formação inicial. O vácuo profundo do espaço intergaláctico não é desprovido de matéria, pois contém alguns átomos de hidrogênio por metro cúbico. [18] Em comparação, o ar que os humanos respiram contém cerca de 1025 moléculas por metro cúbico. [19] [20] A baixa densidade da matéria no espaço exterior significa que a radiação eletromagnética pode viajar grandes distâncias sem ser espalhada: o caminho livre médio de um fóton no espaço intergaláctico é de cerca de 1023 km, ou 10 bilhões de anos-luz. [21] Apesar disso, a extinção, que é a absorção e espalhamento de fótons por poeira e gás, é um fator importante na astronomia galáctica e intergaláctica. [22]",
  },

  de: {
    welcomeMsg:
      "Willkommen bei Internationalization Test Prototype With VueJS und i18n",
    guide: "Kurze Erklärung des Weltraums",
    text:
      "Der Weltraum ist die Weite, die jenseits der Erde und zwischen Himmelskörpern existiert. Der Weltraum ist nicht vollständig leer - es ist ein hartes Vakuum, das eine geringe Teilchendichte enthält, vorwiegend ein Plasma aus Wasserstoff und Helium sowie elektromagnetische Strahlung, Magnetfelder, Neutrinos, Staub und kosmische Strahlung. Die Grundtemperatur des Weltraums, die durch die Hintergrundstrahlung des Urknalls bestimmt wird, beträgt 2,7 Kelvin (–270,45 ° C; –454,81 ° F). [1] Das Plasma zwischen Galaxien macht etwa die Hälfte der baryonischen (gewöhnlichen) Materie im Universum aus; es hat eine Zahlendichte von weniger als einem Wasserstoffatom pro Kubikmeter und eine Temperatur von Millionen Kelvin. [2] Lokale Materiekonzentrationen haben sich zu Sternen und Galaxien verdichtet. Studien zeigen, dass 90% der Masse in den meisten Galaxien in einer unbekannten Form vorliegt, der sogenannten Dunklen Materie, die durch Gravitationskräfte, aber nicht durch elektromagnetische Kräfte mit anderer Materie interagiert. [3] [4] Beobachtungen legen nahe, dass der Großteil der Massenenergie im beobachtbaren Universum dunkle Energie ist, eine Art Vakuumenergie, die kaum verstanden wird. [5] [6] Der intergalaktische Raum nimmt den größten Teil des Universums ein, aber selbst Galaxien und Sternensysteme bestehen fast ausschließlich aus leerem Raum.",
    formationTitle: "Bildung und Zustand",
    formationText:
      " Die Größe des gesamten Universums ist unbekannt und kann unendlich groß sein. [9] Nach der Urknalltheorie war das sehr frühe Universum vor etwa 13,8 Milliarden Jahren ein extrem heißer und dichter Zustand [10], der sich rasch ausdehnte. Ungefähr 380.000 Jahre später hatte sich das Universum ausreichend abgekühlt, damit sich Protonen und Elektronen verbinden und Wasserstoff bilden konnten - die sogenannte Rekombinationsepoche. Als dies geschah, wurden Materie und Energie entkoppelt, so dass sich Photonen frei durch den sich ständig erweiternden Raum bewegen konnten. [11] Materie, die nach der anfänglichen Expansion übrig blieb, hat seitdem einen Gravitationskollaps erfahren, um Sterne, Galaxien und andere astronomische Objekte zu erzeugen, wobei ein tiefes Vakuum zurückbleibt, das den heutigen Weltraum bildet. [12] Da Licht eine endliche Geschwindigkeit hat, beschränkt diese Theorie auch die Größe des direkt beobachtbaren Universums. [11].",
    enviromentTitle: "Umgebung",
    enviromentText:
      "Der Weltraum ist die bekannteste Annäherung an ein perfektes Vakuum. Es hat praktisch keine Reibung und ermöglicht es Sternen, Planeten und Monden, sich nach der anfänglichen Formationsphase frei entlang ihrer idealen Umlaufbahnen zu bewegen. Das tiefe Vakuum des intergalaktischen Raums ist nicht frei von Materie, da es einige Wasserstoffatome pro Kubikmeter enthält. [18] Zum Vergleich: Die Luft, die Menschen atmen, enthält etwa 1025 Moleküle pro Kubikmeter. [19] [20] Die geringe Materiedichte im Weltraum bedeutet, dass elektromagnetische Strahlung große Entfernungen zurücklegen kann, ohne gestreut zu werden: Der mittlere freie Weg eines Photons im intergalaktischen Raum beträgt etwa 1023 km oder 10 Milliarden Lichtjahre. [21] Trotzdem ist das Aussterben, dh die Absorption und Streuung von Photonen durch Staub und Gas, ein wichtiger Faktor in der galaktischen und intergalaktischen Astronomie. [22]",
  },
};

const i18n = new VueI18n({
  locale: "en",
  fallbackLocale: "es", // set fallback locale
  messages, // set locale messages
});

export default i18n;
